# Generated by Django 2.1.5 on 2019-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0003_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/list-icons', verbose_name='avatar'),
        ),
    ]
