# Generated by Django 2.1.5 on 2019-01-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0006_gamelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='game_backend.Profile')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='game_backend.Profile')),
            ],
        ),
    ]
