# Generated by Django 2.1.5 on 2019-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0007_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userreview',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
