# Generated by Django 2.1.5 on 2019-01-20 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0010_auto_20190119_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='online_player',
            field=models.IntegerField(default=0),
        ),
    ]
