# Generated by Django 2.1.5 on 2019-01-20 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0011_auto_20190120_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='dice_numer',
            new_name='dice_number',
        ),
        migrations.AddField(
            model_name='gamelog',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamereview',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
