# Generated by Django 2.1.5 on 2019-01-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0012_auto_20190120_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('friend_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_player', to='game_backend.Profile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_backend.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
