# Generated by Django 2.1.5 on 2019-01-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0013_auto_20190120_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
