# Generated by Django 2.1.5 on 2019-01-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0014_auto_20190120_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='game_backend.Profile'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='game_backend.Profile'),
        ),
    ]
