# Generated by Django 2.1.5 on 2019-01-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0013_profile_date_added'),
        ('game_backend', '0015_auto_20190120_1824'),
    ]

    operations = [
    ]
